title: Dr. Julien Cumin
url: "http://juliencumin.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./orange_logo.png"

tracking_id: #

footer: yes
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Publications"
   link: "publications"
 - name: "Skills"
   link: "skills"
 - name: "Students"
   link: "students"
