title: Dr. Julien Cumin
url: "https://jcumin.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./orange_logo.png"

tracking_id: #

#footer: yes
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "Datasets"
   link: "datasets"
 - name: "Publications"
   link: "publications"
 - name: "Skills"
   link: "skills"
 - name: "Students"
   link: "students"
 - name: "Misc."
   link: "misc"
